name: Hourly PR Data Update

on:
  schedule:
    # 1時間ごとに実行（UTC時間）
    - cron: "0 * * * *"
  workflow_dispatch: # 手動実行も可能にする

jobs:
  update-pr-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pr_analysis repository
        uses: actions/checkout@v3
        with:
          repository: team-mirai-volunteer/pr_analysis
          token: ${{ secrets.GH_TOKEN }}
          path: pr_analysis

      - name: Checkout pr-data repository
        uses: actions/checkout@v3
        with:
          repository: team-mirai-volunteer/pr-data
          token: ${{ secrets.GH_TOKEN }}
          path: pr-data

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          cd pr_analysis
          pip install -r requirements.txt

      - name: Run PR data update script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd pr_analysis
          python src/collectors/pr_collector_main.py --output-dir ../pr-data/prs
          echo "PR data update completed"

      - name: Generate Label Markdown files
        run: |
          cd pr_analysis
          python src/generators/label_report_main.py --input ../pr-data/prs --output-dir ../pr-data/reports/labels
          echo "Label reports generated"

      - name: Generate Section Analysis Report
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd pr_analysis
          python src/analyzers/section_analyzer_main.py --input ../pr-data/prs --output ../pr-data/reports/sections/section_report.md
          echo "Section analysis report generated"

      - name: Commit and push to pr-data repository
        run: |
          cd pr-data
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # PRデータファイルの追加
          if [ -d "prs" ]; then
            git add prs/
          fi
          
          # インデックスファイルの追加
          if [ -d "indexes" ]; then
            git add indexes/
          fi
          
          # レポートファイルの追加
          if [ -d "reports" ]; then
            git add reports/
          fi
          
          # 最後の実行情報ファイルの追加
          if [ -f "prs/last_run_info.json" ]; then
            git add prs/last_run_info.json
            echo "Added last_run_info.json to commit"
          fi
          
          # 変更がある場合のみコミットする
          if git diff --staged --quiet; then
            echo "No changes to commit for pr-data repository"
          else
            timestamp=$(TZ=Asia/Tokyo date '+%Y-%m-%d %H:%M:%S JST')
            git commit -m "Update PR data and reports - ${timestamp}"
            git push
            echo "Changes pushed to pr-data repository"
          fi
